t3widget_include = include_directories(
    '../../deps/t3widget/src',
    '../../deps/t3widget/src/dialogs',
    '../../deps/t3widget/src/widgets',
    '.',
)

widget_shared = custom_target(
    'widget-shared-source',
    input: '../../deps/t3shared/src/shared.c',
    output: 'widget_shared.cc',
    command: [python, codegen, 'shared', 'widget', '@INPUT@', '@OUTPUT@'],
)

t3widget_lib = shared_library(
    't3widget',
    files(
        '../../deps/t3widget/src/autocompleter.cc',
        '../../deps/t3widget/src/clipboard.cc',
        '../../deps/t3widget/src/colorscheme.cc',
        '../../deps/t3widget/src/contentlist.cc',
        '../../deps/t3widget/src/findcontext.cc',
        '../../deps/t3widget/src/interfaces.cc',
        '../../deps/t3widget/src/key.cc',
        '../../deps/t3widget/src/key_binding.cc',
        '../../deps/t3widget/src/log.cc',
        '../../deps/t3widget/src/main.cc',
        '../../deps/t3widget/src/modified_xxhash.cc',
        '../../deps/t3widget/src/mouse.cc',
        '../../deps/t3widget/src/pcre_compat.cc',
        '../../deps/t3widget/src/string_view.cc',
        '../../deps/t3widget/src/stringmatcher.cc',
        '../../deps/t3widget/src/textbuffer.cc',
        '../../deps/t3widget/src/textline.cc',
        '../../deps/t3widget/src/tinystring.cc',
        '../../deps/t3widget/src/undo.cc',
        '../../deps/t3widget/src/util.cc',
        '../../deps/t3widget/src/wrapinfo.cc',
        '../../deps/t3widget/src/dialogs/attributepickerdialog.cc',
        '../../deps/t3widget/src/dialogs/dialog.cc',
        '../../deps/t3widget/src/dialogs/dialogbase.cc',
        '../../deps/t3widget/src/dialogs/filedialog.cc',
        '../../deps/t3widget/src/dialogs/finddialog.cc',
        '../../deps/t3widget/src/dialogs/gotodialog.cc',
        '../../deps/t3widget/src/dialogs/inputselectiondialog.cc',
        '../../deps/t3widget/src/dialogs/insertchardialog.cc',
        '../../deps/t3widget/src/dialogs/mainwindow.cc',
        '../../deps/t3widget/src/dialogs/menupanel.cc',
        '../../deps/t3widget/src/dialogs/messagedialog.cc',
        '../../deps/t3widget/src/dialogs/popup.cc',
        '../../deps/t3widget/src/widgets/bullet.cc',
        '../../deps/t3widget/src/widgets/button.cc',
        '../../deps/t3widget/src/widgets/checkbox.cc',
        '../../deps/t3widget/src/widgets/colorpicker.cc',
        '../../deps/t3widget/src/widgets/editwindow.cc',
        '../../deps/t3widget/src/widgets/expander.cc',
        '../../deps/t3widget/src/widgets/expandergroup.cc',
        '../../deps/t3widget/src/widgets/filepane.cc',
        '../../deps/t3widget/src/widgets/frame.cc',
        '../../deps/t3widget/src/widgets/label.cc',
        '../../deps/t3widget/src/widgets/listpane.cc',
        '../../deps/t3widget/src/widgets/menu.cc',
        '../../deps/t3widget/src/widgets/menuitem.cc',
        '../../deps/t3widget/src/widgets/multiwidget.cc',
        '../../deps/t3widget/src/widgets/scrollbar.cc',
        '../../deps/t3widget/src/widgets/smartlabel.cc',
        '../../deps/t3widget/src/widgets/separator.cc',
        '../../deps/t3widget/src/widgets/split.cc',
        '../../deps/t3widget/src/widgets/textfield.cc',
        '../../deps/t3widget/src/widgets/textwindow.cc',
        '../../deps/t3widget/src/widgets/widget.cc',
        '../../deps/t3widget/src/widgets/widgetgroup.cc',
    ),
    widget_shared,
    generated_headers,
    include_directories: [generated_include, t3widget_include, unistring_inc],
    cpp_args: [
        '-DT3_WIDGET_BUILD_DSO',
        '-DT3_DONT_CHECK_VERSION',
        '-D__STDC_LIMIT_MACROS',
        '-D__STDC_CONSTANT_MACROS',
        '-D_T3_WIDGET_DEBUG',
        '-D_T3_WIDGET_INTERNAL',
        '-DHAS_STRDUP',
        '-DHAS_DLFCN',
        '-DPCRE2_CODE_UNIT_WIDTH=8',
    ],
    dependencies: [
        t3window_dep,
        transcript_dep,
        t3key_dep,
        pcre2_dep,
        unistring_dep,
        threads_dep,
        m_dep,
    ],
    gnu_symbol_visibility: 'hidden',
    install: true,
)

t3widget_dep = declare_dependency(
    link_with: t3widget_lib,
    include_directories: [generated_include, t3widget_include],
    dependencies: [
        t3window_dep,
        transcript_dep,
        t3key_dep,
        pcre2_dep,
        unistring_dep,
    ],
)
