#!/usr/bin/env python3

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path


T3_COMPONENTS = ("config", "key", "highlight", "window", "widget")


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


def copy_if_changed(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and source.read_bytes() == destination.read_bytes():
        return
    shutil.copy2(source, destination)


def transform_shared(component: str, content: str) -> str:
    return content.replace("SHARED", component.upper()).replace("shared", component)


def generate_headers(repo: Path, destination: Path, stamp: Path) -> None:
    mappings = {
        "transcript": repo / "deps/transcript/src",
        "tilde": repo / "src",
    }
    mappings.update(
        {
            f"t3{component}": repo / f"deps/t3{component}/src"
            for component in T3_COMPONENTS
        }
    )

    for public_name, source_root in mappings.items():
        target_root = destination / public_name
        for source in source_root.rglob("*.h"):
            copy_if_changed(source, target_root / source.relative_to(source_root))

    shared_root = repo / "deps/t3shared/src"
    for component in T3_COMPONENTS:
        target_root = destination / f"t3{component}"
        for kind in ("api", "errors"):
            content = transform_shared(component, (shared_root / f"{kind}.h").read_text())
            write_if_changed(target_root / f"{component}_{kind}.h", content)

    write_if_changed(stamp, "/* Generated public-header tree. */\n")


def generate_shared(component: str, source: Path, destination: Path) -> None:
    write_if_changed(destination, transform_shared(component, source.read_text()))


def generate_bytes(source: Path, destination: Path) -> None:
    kept_lines = []
    for line in source.read_text().splitlines():
        stripped = line.lstrip()
        if not stripped or stripped.startswith("#"):
            continue
        kept_lines.append(stripped)
    data = ("\n".join(kept_lines) + "\n").encode()
    values = [f"0x{byte:02x}" for byte in data]
    rows = [", ".join(values[index : index + 12]) for index in range(0, len(values), 12)]
    write_if_changed(destination, ",\n".join(rows) + "\n")


def generate_lex_hide(source: Path, destination: Path) -> None:
    declaration = re.compile(r"^(?:void|int|FILE|YY_EXTRA_TYPE|YY_BUFFER_STATE).*;")
    lines = [
        "/* This file is automatically generated from lex.c. DO NOT EDIT. */",
        "#ifndef LEX_HIDE_H",
        "#define LEX_HIDE_H",
        "",
    ]
    lines.extend(
        f"T3_CONFIG_LOCAL {line}"
        for line in source.read_text().splitlines()
        if declaration.match(line)
    )
    lines.extend(("", "#endif", ""))
    write_if_changed(destination, "\n".join(lines))


def generate_transcript_links(
    linkltc: Path, stamp: Path, modules: list[Path]
) -> None:
    subprocess.run([str(linkltc), *map(str, modules)], check=True)
    write_if_changed(stamp, "Transcript converter aliases generated.\n")


def main(argv: list[str]) -> int:
    command = argv[1]
    if command == "headers":
        generate_headers(Path(argv[2]), Path(argv[3]), Path(argv[4]))
    elif command == "shared":
        generate_shared(argv[2], Path(argv[3]), Path(argv[4]))
    elif command == "bytes":
        generate_bytes(Path(argv[2]), Path(argv[3]))
    elif command == "lex-hide":
        generate_lex_hide(Path(argv[2]), Path(argv[3]))
    elif command == "transcript-links":
        generate_transcript_links(
            Path(argv[2]), Path(argv[3]), [Path(value) for value in argv[4:]]
        )
    else:
        raise SystemExit(f"unknown command: {command}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
